### ISSUE TITLE
SETTINGS_ENABLE_PUSH 

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#10]
From Spencer:

> I know a lot of things changed in this draft since I early-reviewed -01 - I'm now early-reviewing -07 - but I'm not sure that my previous observation about this HTTP setting
> 
> 0x02     SETTINGS_ENABLE_PUSH (a BCP14 “MUST”)
> 
> has been addressed.
> 
> As I pointed out in my previous review RFC 9114 reserves this value in the parallel HTTP/3 registry (https://www.rfc-editor.org/rfc/rfc9114.html#iana-setting-table), and says this about these reserved values in https://www.rfc-editor.org/rfc/rfc9114.html#section-7.2.4.1:
> [7.2.4.1. ](https://datatracker.ietf.org/doc/html/rfc9114#section-7.2.4.1)[Defined SETTINGS Parameters](https://datatracker.ietf.org/doc/html/rfc9114#name-defined-settings-parameters)
> 
> Setting identifiers that were defined in [[HTTP/2](https://datatracker.ietf.org/doc/html/rfc9113)] where there is no corresponding HTTP/3 setting have also been reserved ([Section 11.2.2](https://datatracker.ietf.org/doc/html/rfc9114#iana-settings)). These reserved settings MUST NOT be sent, and their receipt MUST be treated as a [connection error](https://datatracker.ietf.org/doc/html/rfc9114#errors) of type [H3_SETTINGS_ERROR](https://datatracker.ietf.org/doc/html/rfc9114#H3_SETTINGS_ERROR).[¶](https://datatracker.ietf.org/doc/html/rfc9114#section-7.2.4.1-5)
> 
> I don't know what needs to be changed in this specification to reflect this, but even the abstract and the last paragraph of the Introduction refer to "native HTTP/2 or HTTP/3 server push".
> 
> Section 2.4 and 2.5 address the use of TIPS inside an HTTP/1.x connection, which doesn't support server push, so I know you folks have thought about how that works.Do you need to address this for HTTP/3 as well? 
> 
> More strategically, should you be encouraging clients to add support for server PUSH in a new application protocol, if it's already been removed from HTTP/3? But I see this document is in WGLC now, so you can think about that and Do The Right Thing. 
> 
> I have some BCP 14 questions about this text in

**Comment by lkeller19** [comment]
From Kai's response in the mailing list: https://mailarchive.ietf.org/arch/msg/art/wz6ePe0muhOiQTAoHVM-0FY4vHc/

KAI: Thanks for the comment. The current text does not work for HTTP/3, as you mentioned that the initialization of server push has changed in HTTP/3. However, it does not mean that the support for server push is removed in HTTP/3. We will update section 7.2 to specify how to enable server push in HTTP/3 using the procedure in https://www.rfc-editor.org/rfc/rfc9114.html#name-server-push.
