### ISSUE TITLE
Section 3.3

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#11]
From Spencer

> [3.3. ](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#section-3.3)[Uses](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#name-uses)
> 
> This set may be any subset of the ALTO server's network information resources and may include resources defined in linked IRDs. However, it is RECOMMENDED that the ALTO server selects a set that is closed under the resource dependency relationship. That is, if a TIPS' "uses" set includes resource R1 and resource R1 depends on ("uses") resource R0, then the TIPS' "uses" set SHOULD include R0 as well as R1. For example, a TIPS for a cost map SHOULD also provide a TIPS view for the network map upon which that cost map depends.
> 
> I have the same question about R1 and R0, but let's start with a specific case. If a TIPS for a cost map does not also provide a TIPS view for the underlying network map, what happens next? 
> 
> (Nit) is there a missing term after TIPS in "a TIPS for a cost map" in this paragraph?

**Comment by lkeller19** [comment]
Response from Kai in the mailing list: https://mailarchive.ietf.org/arch/msg/art/wz6ePe0muhOiQTAoHVM-0FY4vHc/

KAI: Thanks for the comment. If the TIPS (service) only provides a TIPS view for the cost map but not for the network map, the client will not be able to receive incremental updates about the network map. Thus, when there is a change to the network map, the change will be reflected in a TIPS incremental update of the cost map where the "depentdent-vtags" field will be updated (see https://datatracker.ietf.org/doc/html/rfc7285#section-11.2.3.6). Then, the client knows the mapping between IP prefixes and the PID values has changed but does not know the details. The client needs to query the dependent network map resource to get the new mapping.

> (Nit) is there a missing term after TIPS in "a TIPS for a cost map" in this paragraph?

KAI: Not exactly but the text is a bit unclear. We propose to use the following text instead:

..., if a TIPS service provides a TIPS view for a cost map, it SHOULD also provide a TIPS view for the network map upon which that cost map depends.
