### ISSUE TITLE
Section 4.4  Close Request

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#12]
From Spencer:

In [4.4. ](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#section-4.4)[Close Request](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#name-close-request)

An ALTO client can indicate it no longer desires to pull/receive updates for a specific network resource by "deleting" the TIPS view using the returned tips-view-uri and the HTTP DELETE method. Whether or not the server actually deletes the TIPS view is implementation dependent. Likely, a server will remove the client from a dependency set associated with the TIPS view. A server will not want to delete a TIPS view if another client is using it.

I'm guessing here, but this looks like it's conflating client usage with server storage management. If client A says "delete the TIPS view", and no other client is using it, that view is deleted, but if another client is using it, and the view is not deleted, what happens next? I could imagine that a server might delete the underlying TIPS view when all clients who were using it have deleted it. Does server behavior in this case need to be implementation dependent?

**Comment by lkeller19** [comment]
Response from Kai in the mailing list: https://mailarchive.ietf.org/arch/msg/art/wz6ePe0muhOiQTAoHVM-0FY4vHc/

KAI: Thanks for the comment. From a client's point of view, it sees only one copy of the TIPS view for any resource. However, on the server side, there are different implementation options, especially for common resources (e.g., network map or cost map) that may be frequently queried by many clients:

- create multiple copies, one for each client --> when the client deletes the view, delete it in the server storage
- create one copy for all clients
  - maintain a refcount --> when refcount == 0, delete
  - never delete (thus no need to maintain the client usage)

I think this is implementation dependent. Maybe the text is somehow misleading, how about the following?

...Whether or not the server actually deletes the TIPS view is implementation dependent. For example, an ALTO server may maintain a set of clients that subscribe to the TIPS view of a resource: a client that deletes the view is removed from the set, and the TIPS view is only removed when the dependent set becomes empty.
