### ISSUE TITLE
Clarifications

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#13]
From Spencer

> [8.1. ](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#section-8.1)[Considerations for Load Balancing](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#name-considerations-for-load-bal)
> TIPS allow clients to make concurrent pulls of the incremental updates potentianlly through different HTTP connections. As a consequence, it introduces additional complexties when the ALTO server is being load balanced -- a feature widely used to build scalable and fault-tolerant web services. For example, a request may be incorrectly processed if
> 
> •	the backend servers are stateful, i.e., the TIPS view is created and stored only on a single server;
> 
> •	the ALTO server is using layer-4 load balancing, i.e., the requests are distributed based on the TCP 5-tuple.
> 
> are these conditions ANDed, or ORed? Is either condition sufficient to cause a problem, or are both required?
> 
> Also, in the last paragraph of this section, 
> 
> •	For example, the ALTO server may configure layer-7 load balancers that distribute requests based on URL or cookies.
> 
> Isn't this talking something that an operator or provider of the ALTO server would do, rather than the ALTO server itself?
> 
> I have a similar question about 
> [8.2. ](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#section-8.2)[Considerations for Choosing Updates](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#name-considerations-for-choosing)
> TIPS should be cognizant of the effects of its update schedule, which includes both the choice of timing (i.e., when/what to trigger an update on the updates graph) and the choice of message format (i.e., given an update, send a full replacement or an incremental change).
> 
> and
> 
> Therefore, each TIPS may decide on its own whether to use JSON merge patch or JSON patch according to the changes in network maps.
> 
> is TIPS thinking, or is that up to a human? 
> 
> And in 
> [8.6. ](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#section-8.6)[Considerations for Updates to Ordinal Mode Costs](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-07#name-considerations-for-updates-t)
> While this document allows TIPS to offer incremental updates for ordinal mode cost maps, TIPS implementors should be aware that incremental updates for ordinal costs are more complicated than for numerical costs, and ALTO clients should be aware that small changes may result in large updates.
> 
> I'm guessing that ALTO clients aren't aware. 
> 
> I'm not sure I've caught all of these occurrences, but perhaps the GenArt reviewer will notice others, if they are present!

**Comment by emiapwil** [comment]
Please see below the responses and proposed changes.

1. The two conditions need to both be true to cause the problem.

> For example, a request may be incorrectly processed if the following conditions both hold

2. Yes, it should be the operator/provider of the ALTO server than the server itself

> For example, the operator or the provider of the ALTO server may configure layer-7 load balancers that distribute requests based on URLs or cookies.

3. It's some human.

> When implementing TIPS, programmers should be cognizant of the effects of the update schedule

and 

> Therefore, each TIPS service instance may choose to encode the updates using JSON merge patch or JSON patch based on the changes in network maps.

4. No, the client need not know the issue.

> ..., TIPS implementors should be aware that incremental updates for ordinal costs are more complicated than for numerical costs.

> This complication can be avoided by only offering full replacements as updates when providing TIPS for ordinal cost maps.

**Comment by lkeller19** [comment]
Full response in mailing list: https://mailarchive.ietf.org/arch/msg/art/wz6ePe0muhOiQTAoHVM-0FY4vHc/
