### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#15]
From Martin Thomson

> I'm raising this to the level of a serious issue because this draft is made extraordinarily difficult to understand as a result of this.  Take Section 2.3, which introduces some terms.  That same section then includes completely different terms in Figure 1; terms that turn out to be critical concepts.
> 
> I'll also note, though you might treat this as a separate issue, that while the use of template-like URLs as a convention is a powerful explanatory tool, the draft doesn't make this clear enough.  The use of i and j for instance, are introduced in an example, which is easy to skip, only to find that the rest of the document critically depends on understanding what those mean.

**Comment by emiapwil** [comment]
I feel that we have fixed this issue in the latest revision.

See [section 2.2](https://datatracker.ietf.org/doc/html/draft-ietf-alto-new-transport-08#name-tips-terminology) in -08 and diff [here](https://author-tools.ietf.org/iddiff?url1=draft-ietf-alto-new-transport-07&url2=draft-ietf-alto-new-transport-08&difftype=--html).
