### ISSUE TITLE
Some Nits

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#20]
From Martin Thomson:

> These are just the ones that really jumped out.
> 
> I suggest checking for typos, I saw many.
> 
> Please use proper section references when linking.  Links in the form `<xref target="RFC1234" section="4.5"/>` will ensure that your HTML is properly generated.
> 
> Please submit a bug report for whatever is going on with the caption on Figure 2.  It looks like you have a cross reference in there that xml2rfc is mangling.
> 
> "long pull" is not a thing (Section 2.1)
> 
> "Connection: Closed" is not a thing (Section 4.2)
> 
> Please use real lists (1) especially when the content of the item is long and
> (2) because it makes (a) reading and (b) citing the document easier.
> 
> I can't work out why "next-edge" (Section 5.2) is null when server push is disabled.  Why would a client need to know that only when push is enabled?  If push is enabled, won't the client be pushed the next increment?  On the other hand, if push is disabled, won't the client need to know what to request next?

**Comment by emiapwil** [comment]
Fixed by [9b94550](https://github.com/ietf-wg-alto/draft-ietf-alto-new-transport/commit/9b94550390e4db03dec71e38165af72baf47881e) and [bc92d14](https://github.com/ietf-wg-alto/draft-ietf-alto-new-transport/commit/bc92d1493123186ed1198bd4267b4211bf317a74)
