### ISSUE TITLE
Nits from Secdir 

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#21]
From Donald Eastlake:

> Section 1.0, Page 4:
> OLD
> functioning for HTTP/1.x. TIPS also provides an ALTO server to
> NEW
> functioning for HTTP/1.x. TIPS also provides for an ALTO server to
> 
> Section 2.1.1, Page 8: Seems too vague. A sentence about tips-view-uri wouldn't hurt. At the bottom it says "Use the URI as above". Which URI above? What exactly does "use" mean?
> 
> Section 2.2, Page 9, Figure 3: Figure looks kind of incomplete. Shouldn't there be arrows from R1 to R2/R3?
> 
> Section 2.3, Page 10: In the text on "Information Resource Directory" the first sentence is confusing. What is the thing that is requested to discover? Maybe you should replace "Requested" at the start of the sentence with "Produced when a server is requested"...
> 
> Section 2.3, Page 11 at top: That's Figure 4, not 1.
> 
> Section 2.4, Page 12, 1st paragraph: I think a service runs "over" a connection, not "inside" a connection.
> 
> Section 4.4, Page 23: Seems kind of feeble. How about, given that a disconnect is treated as a DELETE, something like the following, which probably implies that the server maintains a use count. (This document need not mention such a count.)
> OLD
> set associated with the TIPS view. A server will not want to delete
> NEW
> set associated with the TIPS view. A server MUST NOT delete

**Comment by lkeller19** [comment]
Responded to mailing list review and received approval of proposed changes: https://mailarchive.ietf.org/arch/msg/secdir/faTLo_F1R9_FPG03Ea8knNsiar0/
