### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#22]
From Russ White

> This document assumes data will be pushed in the correct order, but it doesn't seem to say this is a requirement. Since the document is dealing with changes to a network topology (for instance), it seems like this would be a requirement to mention someplace. It could be that I missed this requirement, however.

**Comment by lkeller19** [comment]
Responded to mailing list review and updated document accordingly: https://mailarchive.ietf.org/arch/msg/alto/oObG7Fynw-YWXjMHCFbP4XYoi2I/
