### ISSUE TITLE
1:1 connection/client

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#30]
Unless I' m mistaken, I don't see NEW text in the updated version to motivate this design choice:

> Each client maintains a single HTTP connection with the ALTO server and
> uses the TIPS view to retrieve updates.

I thought that we agreed to have such text. Did I missed something? Thanks.

**Comment by emiapwil** [comment]
Sorry I got a flu earlier this week. I should be back on revising the document today. @boucadair
