### ISSUE TITLE
Obsolete RFC 8895?

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#36]
From @martinduke 

> A) Is this intended to obsolete RFC 8895? The example* implies that a server would choose to support both. If this is meant to be the long term state, under what circumstances would a client still use SSE? This document should clarify the relationship. My preference would be to obsolete it, unless there is a compelling use case to retain. Certainly, there is little to no implementation of SSE today, so the cost of deprecation should be low.

**Comment by emiapwil** [comment]
Addressed in [this commit](https://github.com/ietf-wg-alto/draft-ietf-alto-new-transport/commit/cc5ced932c925e2e9ea524517fc7cc95a1594479).
