### ISSUE TITLE
Server Push Motivation

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#37]
from @martinduke 

> B) Can you elaborate on why "The authors have considered these factors and have still decided server push can be valuable in the TIPS use case"? The charter mentions PUSH but we don't need to do it if it's not the right thing.

**Comment by emiapwil** [comment]
Addressed in [this commit](https://github.com/ietf-wg-alto/draft-ietf-alto-new-transport/commit/cc5ced932c925e2e9ea524517fc7cc95a1594479).
