### ISSUE TITLE
S2.1/Websockets

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#38]
from @martinduke:

> (S2.1) This says that clients can currently get ALTO data over WebSockets and cites RFC8895. 8895 does not contain the text "websockets", so I'm wondering what this means.

**Comment by emiapwil** [comment]
Addressed by commit [95da6b](https://github.com/ietf-wg-alto/draft-ietf-alto-new-transport/commit/95da6b9ae41c13c40282fd409ec43257571111e6).
