### ISSUE TITLE
S2.2/TIPS View versions

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#39]
from @martinduke 

 
> (S2.2) It might be worth pointing out in the text that the distinction between tv2 and tv3 has nothing to do with the HTTP version, only the fact that the clients have requested different filter sets.
>

**Comment by emiapwil** [comment]
Addressed by commit [95da6b](https://github.com/ietf-wg-alto/draft-ietf-alto-new-transport/commit/95da6b9ae41c13c40282fd409ec43257571111e6).
