### ISSUE TITLE
S10.2/flow control data

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#40]
from @martinduke 

> (S10.2) TCP, HTTP/2, and QUIC provide stream and connection flow control data limits, and PUSH stream limits, that might help the client that gets too much data.

**Comment by emiapwil** [comment]
Addressed by commit [95da6b](https://github.com/ietf-wg-alto/draft-ietf-alto-new-transport/commit/95da6b9ae41c13c40282fd409ec43257571111e6).
