### ISSUE TITLE
Various Clarifications

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#41]
from @martinduke 

> (S3.1) What is the significance of the "Base Resource" box in Figure 2?
> 
> (S4.3) Client poll actually requires HTTP/1.1, right? 1.0 doesn't have pipelining so it can serve multiple requests. So saying 1.1 instead of 1.x would be more precise.
> 
> (S4.3) and (S9.1) suggest that HTTP/1 can use multiple connections, which implies that the sequence number space is identical for all connections. But (S6) and (S9.7) suggest that the server could issue an entirely different TIPS view with a different sequence number space for the same resource. Can we correct one or add some normative requirements? Is it OK or not for the server to have different sequence number representations of the same resource?
> 
> (S5.2) Where do the values for incremental-change-media-types come from? Is it the registry for media types, with an RFC required to nominate it for use in this field? Does there need to be a new IANA registry? This appears to be an oversight in RFC8895.
> 
> (S5.2) "If the server does not support JSON patch to handle such a case, the server then needs to send a full replacement."
> 
> But if it's long poll, the server can't decide, no? If there's no way to get from 112 to 113, and the client is asking for 112/113, there's no way to resolve this.
> 
> (S5.4) It says the example includes SSE, but I'm scanning for 'text/event-stream' and I'm not finding it. What am I missing?
> 
> (S8.2) What does the server do if the client resets a PUSH_PROMISE? This is kind of a weird phrasing: IIUC PUSH_PROMISE goes on the request stream, so the client is resetting the request stream, not "the PUSH_PROMISE".
> 
> (S8.3) The example should clarify that it is HTTP/2, not 3. Also what is the "current stream"? You mean the original TIPS request stream, right?
> 
> (S8.4) What is "SID_tq"?

**Comment by emiapwil** [comment]
Addressed by commit [95da6b](https://github.com/ietf-wg-alto/draft-ietf-alto-new-transport/commit/95da6b9ae41c13c40282fd409ec43257571111e6).
