### ISSUE TITLE
IANA Actions

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#5]
The current text says: 

> IANA is requested to register the following media type under ALTO registry as defined in [[RFC7285](https://ietf-wg-alto.github.io/draft-ietf-alto-new-transport/draft-ietf-alto-new-transport.html#RFC7285)]:

while the media types should be registered at https://www.iana.org/assignments/media-types/media-types.xhtml#application.

**Comment by emiapwil** [comment]
Indeed ALTO does not have a registry for the media types. Fixed by the latest patch.
