### ISSUE TITLE
Explicit transport requirements

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#7]
From B. Adoba:

> Overall, the document does not lay out the transport requirements explicitly, and so it is hard for me to tell whether the proposed design is optimal or not.
>  In particular, it would be useful to understand the desired reliability vs.
> latency tradeoff, as well as the requirements for backward compatibility (e.g.
> need to operate over HTTP 1.x as well as HTTP/2 and HTTP/3).

**Comment by lkeller19** [comment]
Response from Kai in the mailing list: https://mailarchive.ietf.org/arch/msg/tsv-art/ak3PunrseOcQtrPLEKt763uFVWc/

KAI: You are right and it's a very good suggestion to put forward the
requirements first. We will put a new section in the next revision. Some key
requirements include:

1. Availability: Clients can subscribe at any time and are still able to get
   a complete snapshot.
2. Efficiency: Enable concurrent delivery of the update data. Enable selective
   delivery of update data.
3. Backward compatibility: The mechanism can operate over HTTP/1.x as well as
   HTTP/2 and HTTP/3. The mechanism should reuse constructs from previous ALTO
   standards.
