### ISSUE TITLE
HTTP version constraints

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#8]
From B. Adoba:

> There seems to be a requirement for the protocol to support HTTP 1.x as well as
> HTTP/2 and HTTP/3, but this is not stated explicitly, nor is it justified. In other WGs desiring to use the new capabilities of HTTP/3, a decision has sometimes been made to limit the level of backward compatibility (e.g. support for HTTP/3 and HTTP/2 only) in order to make it possible to take full advantage of the features of HTTP/3.  This decision is easier to make for a new protocol than for one which already has significant HTTP 1.x deployment. So if the transport approach used here is contrained by the existing HTTP/1.x deployments, it would be useful to say so up front.

**Comment by lkeller19** [comment]
Response from Kai in the mailing list: https://mailarchive.ietf.org/arch/msg/tsv-art/ak3PunrseOcQtrPLEKt763uFVWc/

KAI: We will make this requirement explicit in the next revision. Early versions of
this draft does constrain the HTTP version to HTTP/2 and HTTP/3 but after the
discussion with Mark Nottingham (after the HTTP early review) and the chairs, we
realize that the core of the design does not rely on HTTP/2 or HTTP/3. Thus, the
decision is to make the core mechanism independent of HTTP versions but enable
enhanced features when HTTP/2 or HTTP/3 is used.
