### ISSUE TITLE
requirements for reliability and latency 

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-alto/draft-ietf-alto-new-transport#9]
From B. Adoba

> Also, the requirements for reliability and latency are not explicitly laid out.
> The diagrams show incremental update N+1 always depending on update N.  Is this an inherent limitation imposed to meet a requirement, or is it a choice that could potentially be modified? For example, do bad things happen if a client were to obtain a coherent set of information at times N and N+2 but not at time
> N+1? Or would it be better to delay receipt of the N+2 info so as to 
> N+allow for
> the retransmission of N+1 info?

> There is a tradeoff between latency and reliability that can be made if layered coding can be permitted.  For example, if it is possible to modify the dependencies, a client wouldn't necessarily have to obtain every update (e.g.
> if the bandwidth was insufficient to allow them all to be delivered within the required time frame).
> 
> Are there circumstances where such a tradeoff would be desirable?  As an example, there could be a base layer of updates where update N+2 depends on update N, and an extension layer (with higher update frequency) where update
> N+1 depends on update N.  The client could request both layers if it 
> N+could
> handle the higher frequency, or just the base layer if it could not. A diagram describing this kind of two-layer dependency structure is here:
> https://www.w3.org/TR/webrtc-svc/#L1T2*
> 
> ALthough such an approach does have lower coding efficiency, it can potentially respond better to situations in which the client's bandwidth availability can vary substantially, by taking fuller advantage of HTTP/3, allowing the client to restore sync even if a "discardable" update were not delivered, as long as the stream of "non-discardable" updates could be delivered.

**Comment by lkeller19** [comment]
Response from Kai in the mailing list: https://mailarchive.ietf.org/arch/msg/tsv-art/ak3PunrseOcQtrPLEKt763uFVWc/

&gt; Also, the requirements for reliability and latency are not explicitly laid out.
&gt; The diagrams show incremental update N+1 always depending on update N.  Is this
&gt; an inherent limitation imposed to meet a requirement, or is it a choice that
&gt; could potentially be modified? For example, do bad things happen if a client
&gt; were to obtain a coherent set of information at times N and N+2 but not at time
&gt; N+1? Or would it be better to delay receipt of the N+2 info so as to allow for
&gt; the retransmission of N+1 info?
&gt;

KAI: Thanks for the comment. One small clarification: the N and N+1 are not id for
the incremental updates, they actually refer to the logical version of the content.
The content of the data is always the same as long as the updates along a legitimate
path from an old version to the new version are applied sequentially.

It is true that the draft requires that the incremental update from N to N+1 always
exists (to enable long-polling), but it is legitimate to have an incremental update
from N to N+2. So I wouldn't say that it's a choice but it is not a hard constraint
either. Then in the TIPS view the server will return something like:

<tips-view-root>
- ug
  - 0
    - ...
  - N
    - N+1
    - N+2 &lt;----- This indicates an incremental update from N to N+2
  - N+1
    - N+2
  - N+2
    - N+3

Thus, the client can request updates either from N to N+1 and then from N+1 to N+2, or
directly from N to N+2. However, even though the updates can be transmitted in parallel,
they must be applied sequentially, at least with the current coding (JSON merge patch).

To answer your last two questions, let us assume N+2 and N+1 in the question refer
to the update from N+1 to N+2 and from N to N+1.

&gt; Do bad things happen if ...?
Yes, the client may potentially get an incorrect result if it applies update N+2 first. 

&gt; Would it be better to delay ...?
That depends. The client can receive update N+2 first but only applies it after applying
update N+1. This may avoid the idle time if transmitting update N+2 takes longer than
applying update N+1, see below.

Delay:
|---recv n+1---|---retrans n+1---|---recv n+2---|
                                 |-apply n+1-|  |---apply n+2---|

No delay:
|---recv n+1---|---retrans n+1---|
|---recv n+2---|
                                 |-apply n+1-|---apply n+2---|

&gt; There is a tradeoff between latency and reliability that can be made if layered
&gt; coding can be permitted.  For example, if it is possible to modify the
&gt; dependencies, a client wouldn't necessarily have to obtain every update (e.g.
&gt; if the bandwidth was insufficient to allow them all to be delivered within the
&gt; required time frame).
&gt;
&gt; Are there circumstances where such a tradeoff would be desirable?  As an
&gt; example, there could be a base layer of updates where update N+2 depends on
&gt; update N, and an extension layer (with higher update frequency) where update
&gt; N+1 depends on update N.  The client could request both layers if it could
&gt; handle the higher frequency, or just the base layer if it could not. A diagram
&gt; describing this kind of two-layer dependency structure is here:
&gt; https://www.w3.org/TR/webrtc-svc/#L1T2*
&gt;
&gt; ALthough such an approach does have lower coding efficiency, it can potentially
&gt; respond better to situations in which the client's bandwidth availability can
&gt; vary substantially, by taking fuller advantage of HTTP/3, allowing the client
&gt; to restore sync even if a "discardable" update were not delivered, as long as
&gt; the stream of "non-discardable" updates could be delivered.
&gt;

KAI: Thanks for the comment. We believe the current document does support layered
coding: if a server implements layered coding, the updates can be expressed using
the current update graph structure (maybe we should make this more explicit?).
We do not have the concept of "discardable" updates in the document but it is
possible to achieve higher efficiency by discarding some updates. For example, in
Section 5.1 and 7.2.1, we mention that the client (when using pull mode) and the
server (when using push mode) may not necessarily transmit the stepwise updates
but only take shortest paths in the dependency graph -- any update that is not on
the shortest path can be discarded.

I like the idea of layered coding. It may speed up the search of shortest path if
upper layer coding is likely to be "shorter" than lower layer coding, like in skip
lists. However, I am not sure that we have a good sense of how to do layered coding
for ALTO resources or more generally JSON objects right now. How about we can add a
section to discuss "layered coding" as a recommendation for server implementation
first? Then we may seek to standardize that with more analysis and evidences of
the benefits.</tips-view-root></[noreply@ietf.org](mailto:noreply@ietf.org)>
